[general]
host = "0.0.0.0"
port = 5090

[auth]
cookie_max_uses = 7
cookie_storage_size = 2
max_auth_attempts = 3

[timeouts]
cdp = 10

# uncomment if you want to run this without docker
#[dev]
#proxies_list_path = "./proxies.txt"
#targetfp_path = "./xilriws-targetfp"
#proxy_path = "./xilriws-proxy"
#chrome_path = "/path/to/chrome"
#log_level = "DEBUG"
#headless_browser = false
